spring:
  application:
    name: asistencias-uco
  threads:
    virtual:
      enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0

app:
  database:
    mode: fake
  catalogs:
    mode: fake
  security:
    mode: fake
  cache:
    mode: fake
  notifications:
    mode: fake
